# Generated by Django 3.1.4 on 2021-02-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('name', models.TextField()),
                ('votes', models.IntegerField()),
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('poll_uuid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('question', models.TextField()),
                ('uuid', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
