# Generated by Django 3.1.4 on 2021-03-08 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollapp.poll'),
        ),
    ]
